name: Tibia Bazar Monitor

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  check-bazar:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz kod
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalacja bibliotek
        run: |
          pip install requests beautifulsoup4

      - name: Sprawdź bazar
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python check_bazar.py
